### ISSUE TITLE
NoSuchMethodError with Torcherino6.0 and Forge 14.23.1.2566

### ISSUE THREAD

**Issue by smilodon79** [TheRedmoonM/Torcherino#1]
I built this repository and tried it out with direwolf20 1.12 pack and got the following exception with the server crashing on startup.  Apologies if the issue is already known, but thought I'd report it since I didn't see any other defects listed.

Forge Version: 14.23.1.2566
Pack:   direwolf20 1.12 pack

Stack Trace:

// Daisy, daisy...

Time: 1/7/18 6:33 PM
Description: Initializing game

java.lang.NoSuchMethodError: com.sci.torcherino.block.BlockTorcherino.setLightLevel(F)Lnet/minecraft/block/Block;
	at com.sci.torcherino.block.BlockTorcherino.<init>(BlockTorcherino.java:9)
	at com.sci.torcherino.proxy.CommonProxy.registerBlocks(CommonProxy.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_272_CommonProxy_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by JayaramV-Hexaware** [comment]
Just found that BlockTorch class is added in forge version 1.12.2-14.23.1.2587.  The direwolf pack is (as of 45 minutes back) running 1.12.2-14.23.1.2585, which doesn't have the class and hence the problem.  I think the easiest option for me is to just wait a few days until the packs update to the latest version of forge and then I can actually test this mod.

**Comment by smilodon79** [comment]
direwolf20 pack updated to forge 14.23.1.2587.  With that, everything is working fine.  I tested it out in a few scenarios and the torches seem to be working fine.
